import "./globals.css";
import { Manrope } from "next/font/google";
import { cx } from "../utils";
import Header from "@/src//components/Header";
import Footer from "../components/Footer";

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mr",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cx(manrope.variable, "font-mr bg-light dark:bg-dark")}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
